/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 12-may.-2026 1:36:44 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS area_servicio CASCADE
;

DROP TABLE IF EXISTS ciudad CASCADE
;

DROP TABLE IF EXISTS cliente CASCADE
;

DROP TABLE IF EXISTS contrato CASCADE
;

DROP TABLE IF EXISTS correo_cliente CASCADE
;

DROP TABLE IF EXISTS correo_persona CASCADE
;

DROP TABLE IF EXISTS cotizacion CASCADE
;

DROP TABLE IF EXISTS dato_metrologico CASCADE
;

DROP TABLE IF EXISTS encargado CASCADE
;

DROP TABLE IF EXISTS equipo CASCADE
;

DROP TABLE IF EXISTS equipo_cliente CASCADE
;

DROP TABLE IF EXISTS fabricante CASCADE
;

DROP TABLE IF EXISTS marca CASCADE
;

DROP TABLE IF EXISTS modelo CASCADE
;

DROP TABLE IF EXISTS orden_trabajo CASCADE
;

DROP TABLE IF EXISTS pais CASCADE
;

DROP TABLE IF EXISTS persona CASCADE
;

DROP TABLE IF EXISTS protocolo_mantenimiento CASCADE
;

DROP TABLE IF EXISTS reporte_servicio CASCADE
;

DROP TABLE IF EXISTS reporte_servicio_snapshot CASCADE
;

DROP TABLE IF EXISTS representante_legal CASCADE
;

DROP TABLE IF EXISTS sede CASCADE
;

DROP TABLE IF EXISTS telefono_cliente CASCADE
;

DROP TABLE IF EXISTS telefono_persona CASCADE
;

DROP TABLE IF EXISTS tipo_equipo CASCADE
;

DROP TABLE IF EXISTS verificacion_ingreso CASCADE
;

DROP TABLE IF EXISTS verificacion_metrologica CASCADE
;

DROP TABLE IF EXISTS verificacion_tecnica CASCADE
;

DROP TABLE IF EXISTS verificacion_tecnica_tipo_equipo CASCADE
;

/* Create Tables */

CREATE TABLE area_servicio
(
	k_id_area_servicio uuid NOT NULL,	-- ID que se le asigna dentro de la empresa al area de servicio 
	n_nombre_area varchar(50) NOT NULL,	-- Nombre unico con el que se identifica el area de servicio
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_sede uuid NOT NULL	-- ID de la sede donde se esta prestando el area del servicio
)
;

CREATE TABLE ciudad
(
	k_id_ciudad varchar(10) NOT NULL,	-- PK de la ciudad.
	n_nombre_ciudad varchar(50) NOT NULL,	-- Nombre de la ciudad.
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_pais varchar(3) NOT NULL	-- FK que viene desde pais.
)
;

CREATE TABLE cliente
(
	k_id_cliente varchar(11) NOT NULL,	-- iD (NIT juridico, NIT natural, CC) unico con el que se identifica al cliente.
	n_tipo_identificacion varchar(12) NOT NULL,	-- Tipo de documento, este puede ser cedula de ciudadania, cedula extrangera, entre otras 
	n_razon_social varchar(50) NOT NULL,	-- Razon social a la que pertenece al cliente.
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_pais varchar(3) NULL	-- ID unico del pais de donde proviene el usuario 
)
;

CREATE TABLE contrato
(
	k_id_contrato varchar(10) NOT NULL,
	t_estado_contrato varchar(20) NOT NULL,
	f_fecha_inicio date NOT NULL,
	f_fecha_finalizacion date NULL,
	t_observaciones varchar(50) NULL
)
;

CREATE TABLE correo_cliente
(
	k_id_correo_cliente uuid NOT NULL,	-- Este es el PK que representa la los correo_cliente.
	n_correo_cliente varchar(50) NOT NULL,	-- Informacion de contacto del cliente. El correo tiene ciertas especificaciones 
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_cliente varchar(11) NULL	-- ID del cliente con el que esta relacionado el correo electronico 
)
;

CREATE TABLE correo_persona
(
	k_id_correo_persona uuid NOT NULL,	-- Llave primaria de la tabla correo_persona.
	n_correo_persona varchar(50) NOT NULL,	-- Corresponde al correo electrónico de la persona.
	k_identificador uuid NULL,	-- Es la llave foránea que referencia a la tabla persona.
	b_estado_acitivo boolean NOT NULL   DEFAULT true	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
)
;

CREATE TABLE cotizacion
(
	k_id_equipo_cliente uuid NOT NULL,
	k_id_contrato varchar(10) NULL,
	m_valor_unitario_mantenimiento bigint NOT NULL,
	m_valor_total bigint NOT NULL,
	t_observacion varchar(250) NULL,
	f_fecha_emision date NOT NULL,
	f_validez date NOT NULL,
	t_estado_cotizacion varchar(20) NOT NULL
)
;

CREATE TABLE dato_metrologico
(
	d_valor numeric(10,4) NOT NULL,	-- Es el valor de valor de verificación predeterminada.
	n_tipo varchar(50) NOT NULL,	-- Este es el tipo de valor que se va a verificar (kg, %...)
	k_id_tipo_equipo uuid NULL,	-- FK que viene desde tipo_equipo.
	b_estado_activo boolean NOT NULL   DEFAULT true
)
;

CREATE TABLE encargado
(
	k_identificador uuid NOT NULL,	-- Esta es la FK que viene desde la persona.
	t_tipo_encargado varchar(16) NOT NULL,	-- Esta columna es la encargada de guardar el tipo de encargado que es.
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_area_servicio uuid NULL,	-- Esta es la FK que viene desde el area de servicio.
	k_id_sede uuid NULL	-- Esta es la FK que viene desde la sede.
)
;

CREATE TABLE equipo
(
	k_id_equipo uuid NOT NULL,	-- PK que diferencia a los equipo.
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_tipo_equipo uuid NOT NULL,	-- FK que viene desde el tipo_equipo.
	k_id_marca uuid NOT NULL	-- Fk que viene desde la marca.
)
;

CREATE TABLE equipo_cliente
(
	k_id_equipo_cliente uuid NOT NULL,	-- PK que diferencia a los equipos que pertenecen al cliente.
	k_serie varchar(50) NOT NULL,	-- Numero de serie que pertenece al equipo.
	f_fecha_compra date NULL,	-- Fecha en la que el cliente compra el equipo.
	v_valor_compra bigint NULL,	-- Precio que tuvo que pagar el cliente para tener el equipo.
	n_no_inventario varchar(50) NULL,	-- Numero de inventario que da el cliente a su equipo.
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_area_servicio uuid NULL,	-- ID del area del servicio el cual otorga el equipo a cliente.
	k_id_modelo uuid NULL	-- FK que viene desde el modelo.
)
;

CREATE TABLE fabricante
(
	k_id_fabricante uuid NOT NULL,	-- PK con el que se identifica el fabricante dentro de la empresa.
	n_nombre_fabricante varchar(50) NOT NULL,	-- Nombre del fabricante.
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_pais varchar(3) NULL	-- FK del pais de donde proviene el fabricante.
)
;

CREATE TABLE marca
(
	k_id_marca uuid NOT NULL,	-- PK de la marca del equipo.
	n_nombre_marca varchar(50) NULL,	-- Nombre de la marca que tiene cada uno de los equipos.
	b_estado_activo boolean NOT NULL   DEFAULT true	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
)
;

CREATE TABLE modelo
(
	k_id_modelo uuid NOT NULL,	-- PK del modelo del equipo 
	n_invima varchar(50) NULL,	-- Registro invima con el que se encuentra relacionado con el modelo 
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_fabricante uuid NULL,	-- ID del fabricante que ha producido el modelo del equipo
	k_id_equipo uuid NULL	-- FK que vien desde el equipo
)
;

CREATE TABLE orden_trabajo
(
	k_id_orden_trabajo uuid NOT NULL,	-- Llave primaria de la tabla orden_trabajo.
	f_fecha_mantenimiento timestamp without time zone NOT NULL,	-- Esta columna se encargará de guardar la fecha en la que se creó la orden de trabajo.
	n_periodicidad varchar(15) NOT NULL,	-- Este campo guardará la periodicidad de la orden de trabajo (cada cuánto se les realiza mantenimiento a estos equipos).
	k_identificador uuid NULL,	-- Este campo es la FK la persona que representa al ingeniero encargado de la orden de trabajo.
	t_estado_ejecucion varchar(15) NOT NULL   DEFAULT 'CREADO',	-- Este campo es el encargado de reflejar el estado de ejecución de la orden de trabajo (CREADO, EJECUCION, EJECUTADO).
	b_estado_activo boolean NOT NULL   DEFAULT true	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
)
;

CREATE TABLE pais
(
	k_id_pais varchar(3) NOT NULL,	-- ID del pais de donde proviene un fabricante o un cliente 
	n_nombre_pais varchar(20) NOT NULL,	-- nombre del pais de donde puede provenir un fabricante o un cliente 
	b_estado_activo boolean NOT NULL   DEFAULT true	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
)
;

CREATE TABLE persona
(
	k_identificador uuid NOT NULL,	-- ID que se le otorga a la persona de manera interna dentro de la empresa 
	k_cedula varchar(10) NOT NULL,	-- Cédula de la persona utilizada como identificador único.
	n_primer_nombre varchar(50) NOT NULL,	-- Primer nombre de la persona.
	n_segundo_nombre varchar(50) NULL,	-- Segundo nombre de la persona.
	n_primer_apellido varchar(50) NOT NULL,	-- Primer apellido de la persona.
	n_segundo_apellido varchar(50) NULL,	-- Segundo apellido de la persona.
	t_tipo_persona varchar(19) NOT NULL,	-- Tipo de persona que sera (ingeniero, encargado, representante legal)
	t_segundo_tipo_persona varchar(19) NULL,	-- Tipo de persona que sera (encargado, representante legal)
	b_estado_activo varchar(50) NOT NULL   DEFAULT true	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
)
;

CREATE TABLE protocolo_mantenimiento
(
	k_id_verificacion uuid NOT NULL,
	b_ejecucion_protocolo boolean NOT NULL   DEFAULT false,
	k_id_reporte_servicio uuid NULL
)
;

CREATE TABLE reporte_servicio
(
	k_id_reporte_servicio uuid NOT NULL,	-- Es la llave primaria que actúa como identificador único de los reportes de servicio.
	k_id_orden_trabajo varchar(10) NOT NULL,	-- Es la llave foránea que referencia a la tabla orden_de_trabajo.
	k_id_equipo_cliente varchar(10) NOT NULL,	-- Es la llave foránea que referencia a la tabla equipo_cliente.
	k_id_cliente uuid NOT NULL,	-- Es la llave foránea que referencia a la tabla cliente.
	t_observaciones_reporte_servico varchar(250) NULL,
	d_valor_equipo numeric(10,4) NULL,
	d_valor_patron numeric(10,4) NULL,
	t_resultado_verificacion_tecnica varchar(50) NULL
)
;

CREATE TABLE reporte_servicio_snapshot
(
	k_id_reporte_snapshot uuid NOT NULL,
	t_creado timestamp without time zone NOT NULL,
	s_snapshot JSONB NOT NULL
)
;

CREATE TABLE representante_legal
(
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_identificador uuid NOT NULL,	-- FK proveniente de la tabla persona.
	k_id_cliente varchar(11) NOT NULL	--  FK proveniente de la clave cliente.
)
;

CREATE TABLE sede
(
	k_id_sede uuid NOT NULL,	-- ID con el que se identifica la sede dentro de la empresa.
	n_nombre_sede varchar(50) NOT NULL,	-- Nombre de la sede.
	dir_calle varchar(50) NOT NULL,	-- Parte de la dirección que pertenece a la calle.
	dir_carrera varchar(50) NOT NULL,	-- Parte de la dirección que pertenece a la carrera.
	dir_num varchar(50) NOT NULL,	-- Parte de la dirección que pertenece al numero.
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_cliente varchar(11) NOT NULL,	-- FK que viene desde el cliente que representa al dueño de la sede.
	k_id_ciudad varchar(10) NOT NULL	-- ID de la ciudad en donde se encuentra la sede 
)
;

CREATE TABLE telefono_cliente
(
	k_id_telefono_cliente uuid NOT NULL,	-- Esta es la PK que identifica a los telefono_cliente.
	n_telefono_cliente varchar(50) NOT NULL,	-- Número telefonico del cliente 
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_cliente varchar(11) NULL	-- ID del cliente del cual esta relacionado el numero telefonico 
)
;

CREATE TABLE telefono_persona
(
	k_id_telefono_persona uuid NOT NULL,	-- Llave primaria de la tabla telefono_persona.
	n_telefono_persona varchar(10) NOT NULL,	-- Este es el número de teléfono de la persona.
	k_identificador uuid NULL,	-- Es la llave foránea que referencia a la tabla persona.
	b_estado_activo boolean NOT NULL   DEFAULT true	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
)
;

CREATE TABLE tipo_equipo
(
	k_id_tipo_equipo uuid NOT NULL,	-- PK del tipo de equipo.
	n_nombre_tipo_equipo varchar(50) NOT NULL,	-- Nombre del tipo de equipo 
	t_definicion_tecnica varchar(250) NOT NULL,	-- Definicion tecnica del tipo de equipo, en donde se especifica las caracteristicas que tiene este 
	t_recomendaciones_cuidado varchar(250) NOT NULL,	-- Esta columna es la encargado de guardar las recomendaciones de cuidado del tipo_equipo.
	i_voltage integer NULL,	-- Voltage que tiene cada uno de los diferentes equipos
	d_amperaje numeric(2) NULL,	-- Amperaje que tiene cada uno de los diferentes equipos
	t_tecnologia_predominante varchar(50) NOT NULL,	-- Tecnologia predominante que actua en el tipo de equipo 
	b_verificable boolean NOT NULL   DEFAULT false,	-- Esta columan es la encargada de guardar si a este tipo equipo se le hace verificaión metrologica o no.
	m_valor_unitario_mantenimiento bigint NOT NULL,	-- Este es el valor que tendra el matenimiento del tipo_equipo.
	n_tipo_verificacion varchar(50) NULL,	-- Aqui se va a determinar la modalidad de verificación metrologica.
	b_estado_activo boolean NOT NULL   DEFAULT true	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
)
;

CREATE TABLE verificacion_ingreso
(
	k_id_verificacion uuid NOT NULL,
	b_aplica boolean NOT NULL   DEFAULT false,
	b_conformidad_ingreso boolean NOT NULL   DEFAULT false,
	t_observacion_ingreso varchar(250) NULL,
	k_id_reporte_servicio uuid NULL
)
;

CREATE TABLE verificacion_metrologica
(
	d_valor_equipo numeric(10,4) NOT NULL,	-- Este corresponde al valor registrado en la verificación realizada al equipo.
	d_valor_patron numeric(10,4) NOT NULL,	-- Este corresponde al valor registrado del equipo patrón durante la verificación realizada al equipo.
	k_id_reporte_servicio uuid NULL	-- Es la llave foránea que referencia a la tabla reporte_servicio.
)
;

CREATE TABLE verificacion_tecnica
(
	k_id_verificacion uuid NOT NULL,	-- PK de que diferencia a los distintos verificacion_tecnica.
	t_descripcion varchar(250) NOT NULL,	-- Descripcion de la verificacion_metrologica.
	t_tipo_verificacion varchar(25) NOT NULL,	-- Esta columna es la encargada de guardar el tipo de verificacion_metrologica.
	b_estado_activo boolean NOT NULL   DEFAULT true	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
)
;

CREATE TABLE verificacion_tecnica_tipo_equipo
(
	k_id_verificacion uuid NOT NULL,	-- FK que viene desde verificacion_metrologica
	b_estado_activo boolean NOT NULL   DEFAULT true,	-- Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.
	k_id_tipo_equipo uuid NOT NULL	-- FK que viene desde tipo_equipo.
)
;

CREATE TABLE domain_events (
    id              BIGSERIAL       PRIMARY KEY,
    event_id        VARCHAR(36)     NOT NULL UNIQUE,
    aggregate_id    VARCHAR(255)    NOT NULL,
    aggregate_type  VARCHAR(100)    NOT NULL,
    event_type      VARCHAR(255)    NOT NULL,
    version         INT             NOT NULL DEFAULT 1,
    occurred_at     TIMESTAMPTZ     NOT NULL,
    metadata_json   JSONB           NOT NULL,
    payload_json    JSONB           NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_events_aggregate ON domain_events(aggregate_type, aggregate_id);
CREATE INDEX idx_events_type      ON domain_events(event_type);
CREATE INDEX idx_events_occurred  ON domain_events(occurred_at);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE area_servicio ADD CONSTRAINT "PK_area_servicio"
	PRIMARY KEY (k_id_area_servicio)
;

CREATE INDEX "IXFK_area_servicio_sede" ON area_servicio (k_id_sede ASC)
;

ALTER TABLE ciudad ADD CONSTRAINT "PK_ciudad"
	PRIMARY KEY (k_id_ciudad)
;

CREATE INDEX "IXFK_ciudad_pais" ON ciudad (k_id_pais ASC)
;

ALTER TABLE cliente ADD CONSTRAINT "PK_cliente"
	PRIMARY KEY (k_id_cliente)
;

ALTER TABLE cliente ADD CONSTRAINT "CHK_tipo_identifiacion" CHECK (n_tipo_identificacion IN ('NIT_juridico', 'NIT_natural', 'CC', 'CE'))
;

CREATE INDEX "IXFK_cliente_pais" ON cliente (k_id_pais ASC)
;

ALTER TABLE contrato ADD CONSTRAINT "PK_contrato"
	PRIMARY KEY (k_id_contrato)
;

ALTER TABLE contrato ADD CONSTRAINT "CHK_estado_contrato" CHECK (t_estado_contrato IN (
    'borrador',
    'en_revision',
    'aprobado',
    'firmado',
    'activo',
    'suspendido',
    'renovado',
    'vencido',
    'cancelado',
    'rescindido',
    'finalizado'
  ))
;

ALTER TABLE correo_cliente ADD CONSTRAINT "PK_correo_cliente"
	PRIMARY KEY (k_id_correo_cliente)
;

CREATE INDEX "IXFK_correo_cliente_cliente" ON correo_cliente (k_id_cliente ASC)
;

ALTER TABLE correo_persona ADD CONSTRAINT "PK_correo_persona"
	PRIMARY KEY (k_id_correo_persona)
;

CREATE INDEX "IXFK_correo_persona" ON correo_persona (k_identificador ASC)
;

ALTER TABLE cotizacion ADD CONSTRAINT "PK_cotizacin"
	PRIMARY KEY (k_id_equipo_cliente)
;

ALTER TABLE cotizacion ADD CONSTRAINT "CHK_estado_cotizacion" CHECK (t_estado_cotizacion IN (
    'borrador',
    'enviada',
    'aprobada',
    'rechazada',
    'vencida',
    'cancelada',
    'convertida_contrato'
  ))
;

CREATE INDEX "IXFK_cotizacion_contrato" ON cotizacion (k_id_contrato ASC)
;

CREATE INDEX "IXFK_cotizacion_equipo_cliente" ON cotizacion (k_id_equipo_cliente ASC)
;

CREATE INDEX "IXFK_dato_metrologico_tipo_equipo" ON dato_metrologico (k_id_tipo_equipo ASC)
;

ALTER TABLE encargado ADD CONSTRAINT "PK_encargado"
	PRIMARY KEY (k_identificador)
;

ALTER TABLE encargado ADD CONSTRAINT "CHK_tipo_encagado" CHECK (t_tipo_encargado IN ('sede', 'area_servicio'))
;

CREATE INDEX "IXFK_encargado_area_servicio" ON encargado (k_id_area_servicio ASC)
;

CREATE INDEX "IXFK_encargado_persona" ON encargado (k_identificador ASC)
;

CREATE INDEX "IXFK_encargado_sede" ON encargado (k_id_sede ASC)
;

ALTER TABLE equipo ADD CONSTRAINT "PK_equipo"
	PRIMARY KEY (k_id_equipo)
;

CREATE INDEX "IXFK_equipo_marca" ON equipo (k_id_marca ASC)
;

CREATE INDEX "IXFK_equipo_tipo_equipo" ON equipo (k_id_tipo_equipo ASC)
;

ALTER TABLE equipo_cliente ADD CONSTRAINT "PK_equipo_cliente"
	PRIMARY KEY (k_id_equipo_cliente)
;

CREATE INDEX "IXFK_equipo_cliente_area_servicio" ON equipo_cliente (k_id_area_servicio ASC)
;

CREATE INDEX "IXFK_equipo_cliente_modelo" ON equipo_cliente (k_id_modelo ASC)
;

ALTER TABLE fabricante ADD CONSTRAINT "PK_fabricante"
	PRIMARY KEY (k_id_fabricante)
;

CREATE INDEX "IXFK_fabricante_pais" ON fabricante (k_id_pais ASC)
;

ALTER TABLE marca ADD CONSTRAINT "PK_marca"
	PRIMARY KEY (k_id_marca)
;

ALTER TABLE modelo ADD CONSTRAINT "PK_modelo"
	PRIMARY KEY (k_id_modelo)
;

CREATE INDEX "IXFK_modelo_equipo" ON modelo (k_id_equipo ASC)
;

CREATE INDEX "IXFK_modelo_fabricante" ON modelo (k_id_fabricante ASC)
;

ALTER TABLE orden_trabajo ADD CONSTRAINT "PK_mantenimiento"
	PRIMARY KEY (k_id_orden_trabajo)
;

ALTER TABLE orden_trabajo ADD CONSTRAINT "CHK_periodicidad" CHECK (n_periodicidad IN ('mensual', 'trimestral', 'semestral', 'anual'))
;

ALTER TABLE orden_trabajo ADD CONSTRAINT "CHK_estado_ejecucion" CHECK (t_estado_ejecucion IN ('CREADO', 'EJECUCION', 'EJECUTADO'))
;

CREATE INDEX "IXFK_orden_trabajo_persona" ON orden_trabajo (k_identificador ASC)
;

ALTER TABLE pais ADD CONSTRAINT "PK_pais"
	PRIMARY KEY (k_id_pais)
;

ALTER TABLE persona ADD CONSTRAINT "PK_persona"
	PRIMARY KEY (k_identificador)
;

ALTER TABLE persona 
  ADD CONSTRAINT "UQ_cedula" UNIQUE (k_cedula)
;

ALTER TABLE persona ADD CONSTRAINT "CHK_tipo_persona" CHECK (t_tipo_persona IN ('ingeniero', 'encargado', 'representante_legal') AND
t_segundo_tipo_persona IN ('encargado'))
;

-- Primero, crea la función que contiene la lógica
CREATE OR REPLACE FUNCTION validar_roles_persona()
RETURNS TRIGGER AS $$
BEGIN
    -- Regla 1: Si t_tipo_persona es 'ingeniero', no se puede llenar t_segundo_tipo_persona
    IF NEW.t_tipo_persona = 'ingeniero' AND NEW.t_segundo_tipo_persona IS NOT NULL THEN
        RAISE EXCEPTION 'Si t_tipo_persona es "ingeniero", t_segundo_tipo_persona debe ser NULL.';
    END IF;

    -- Regla 2: Si ambos están llenos, no pueden ser iguales
    IF NEW.t_segundo_tipo_persona IS NOT NULL AND NEW.t_tipo_persona = NEW.t_segundo_tipo_persona THEN
        RAISE EXCEPTION 't_tipo_persona y t_segundo_tipo_persona no pueden ser iguales.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
;

CREATE INDEX "IXFK_protocolo_mantenimiento_reporte_servicio" ON protocolo_mantenimiento (k_id_reporte_servicio ASC)
;

ALTER TABLE reporte_servicio ADD CONSTRAINT "PK_reporte_servicio"
	PRIMARY KEY (k_id_reporte_servicio)
;

ALTER TABLE reporte_servicio_snapshot ADD CONSTRAINT "PK_Table3"
	PRIMARY KEY (k_id_reporte_snapshot)
;

ALTER TABLE representante_legal ADD CONSTRAINT "PK_representante_legal"
	PRIMARY KEY (k_identificador,k_id_cliente)
;

CREATE INDEX "IXFK_representante_legal_cliente" ON representante_legal (k_id_cliente ASC)
;

CREATE INDEX "IXFK_representante_legal_persona" ON representante_legal (k_identificador ASC)
;

ALTER TABLE sede ADD CONSTRAINT "PK_sede"
	PRIMARY KEY (k_id_sede)
;

CREATE INDEX "IXFK_sede_ciudad" ON sede (k_id_ciudad ASC)
;

CREATE INDEX "IXFK_sede_cliente" ON sede (k_id_cliente ASC)
;

ALTER TABLE telefono_cliente ADD CONSTRAINT "PK_telefono_cliente"
	PRIMARY KEY (k_id_telefono_cliente)
;

CREATE INDEX "IXFK_telefono_cliente_cliente" ON telefono_cliente (k_id_cliente ASC)
;

ALTER TABLE telefono_persona ADD CONSTRAINT "PK_telefono_persona"
	PRIMARY KEY (k_id_telefono_persona)
;

CREATE INDEX "IXFK_telefono_persona" ON telefono_persona (k_identificador ASC)
;

ALTER TABLE tipo_equipo ADD CONSTRAINT "PK_TipeDeEquipo"
	PRIMARY KEY (k_id_tipo_equipo)
;

ALTER TABLE tipo_equipo ADD CONSTRAINT "CHK_tipo_verificacion" CHECK (n_tipo_verificacion IN ('patron_constante', 'equipo_constante', 'patron_equipo_variable'))
;

CREATE INDEX "IXFK_verificacion_ingreso_reporte_servicio" ON verificacion_ingreso (k_id_reporte_servicio ASC)
;

CREATE INDEX "IXFK_Verificacion metrologica_reporte_servicio" ON verificacion_metrologica (k_id_reporte_servicio ASC)
;

ALTER TABLE verificacion_tecnica ADD CONSTRAINT "PK_verificacion_tecnica"
	PRIMARY KEY (k_id_verificacion)
;

ALTER TABLE verificacion_tecnica ADD CONSTRAINT "CHK_tipo" CHECK (t_tipo_verificacion IN ('VER_TEC_INIC', 'PROC_MANT'))
;

ALTER TABLE verificacion_tecnica_tipo_equipo ADD CONSTRAINT "PK_verificacion_tecnica_tipo_equipo"
	PRIMARY KEY (k_id_verificacion,k_id_tipo_equipo)
;

CREATE INDEX "IXFK_verificacion_tecnica_tipo_equipo_tipo_equipo" ON verificacion_tecnica_tipo_equipo (k_id_tipo_equipo ASC)
;

CREATE INDEX "IXFK_verificacion_tecnica_tipo_equipo_verificacion_tecnica" ON verificacion_tecnica_tipo_equipo (k_id_verificacion ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE area_servicio ADD CONSTRAINT "FK_area_servicio_sede"
	FOREIGN KEY (k_id_sede) REFERENCES sede (k_id_sede) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ciudad ADD CONSTRAINT "FK_ciudad_pais"
	FOREIGN KEY (k_id_pais) REFERENCES pais (k_id_pais) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cliente ADD CONSTRAINT "FK_cliente_pais"
	FOREIGN KEY (k_id_pais) REFERENCES pais (k_id_pais) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE correo_cliente ADD CONSTRAINT "FK_correo_cliente_cliente"
	FOREIGN KEY (k_id_cliente) REFERENCES cliente (k_id_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE correo_persona ADD CONSTRAINT "FK_correo_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cotizacion ADD CONSTRAINT "FK_cotizacion_contrato"
	FOREIGN KEY (k_id_contrato) REFERENCES contrato (k_id_contrato) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cotizacion ADD CONSTRAINT "FK_cotizacion_equipo_cliente"
	FOREIGN KEY (k_id_equipo_cliente) REFERENCES equipo_cliente (k_id_equipo_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dato_metrologico ADD CONSTRAINT "FK_dato_metrologico_tipo_equipo"
	FOREIGN KEY (k_id_tipo_equipo) REFERENCES tipo_equipo (k_id_tipo_equipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE encargado ADD CONSTRAINT "FK_encargado_area_servicio"
	FOREIGN KEY (k_id_area_servicio) REFERENCES area_servicio (k_id_area_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE encargado ADD CONSTRAINT "FK_encargado_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE encargado ADD CONSTRAINT "FK_encargado_sede"
	FOREIGN KEY (k_id_sede) REFERENCES sede (k_id_sede) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE equipo ADD CONSTRAINT "FK_equipo_marca"
	FOREIGN KEY (k_id_marca) REFERENCES marca (k_id_marca) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE equipo ADD CONSTRAINT "FK_equipo_tipo_equipo"
	FOREIGN KEY (k_id_tipo_equipo) REFERENCES tipo_equipo (k_id_tipo_equipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE equipo_cliente ADD CONSTRAINT "FK_equipo_cliente_area_servicio"
	FOREIGN KEY (k_id_area_servicio) REFERENCES area_servicio (k_id_area_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE equipo_cliente ADD CONSTRAINT "FK_equipo_cliente_modelo"
	FOREIGN KEY (k_id_modelo) REFERENCES modelo (k_id_modelo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE fabricante ADD CONSTRAINT "FK_fabricante_pais"
	FOREIGN KEY (k_id_pais) REFERENCES pais (k_id_pais) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE modelo ADD CONSTRAINT "FK_modelo_equipo"
	FOREIGN KEY (k_id_equipo) REFERENCES equipo (k_id_equipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE modelo ADD CONSTRAINT "FK_modelo_fabricante"
	FOREIGN KEY (k_id_fabricante) REFERENCES fabricante (k_id_fabricante) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE orden_trabajo ADD CONSTRAINT "FK_orden_trabajo_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE protocolo_mantenimiento ADD CONSTRAINT "FK_protocolo_mantenimiento_reporte_servicio"
	FOREIGN KEY (k_id_reporte_servicio) REFERENCES reporte_servicio (k_id_reporte_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE representante_legal ADD CONSTRAINT "FK_representante_legal_cliente"
	FOREIGN KEY (k_id_cliente) REFERENCES cliente (k_id_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE representante_legal ADD CONSTRAINT "FK_representante_legal_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sede ADD CONSTRAINT "FK_sede_ciudad"
	FOREIGN KEY (k_id_ciudad) REFERENCES ciudad (k_id_ciudad) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sede ADD CONSTRAINT "FK_sede_cliente"
	FOREIGN KEY (k_id_cliente) REFERENCES cliente (k_id_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE telefono_cliente ADD CONSTRAINT "FK_telefono_cliente_cliente"
	FOREIGN KEY (k_id_cliente) REFERENCES cliente (k_id_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE telefono_persona ADD CONSTRAINT "FK_telefono_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE verificacion_ingreso ADD CONSTRAINT "FK_verificacion_ingreso_reporte_servicio"
	FOREIGN KEY (k_id_reporte_servicio) REFERENCES reporte_servicio (k_id_reporte_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE verificacion_metrologica ADD CONSTRAINT "FK_Verificacion metrologica_reporte_servicio"
	FOREIGN KEY (k_id_reporte_servicio) REFERENCES reporte_servicio (k_id_reporte_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE verificacion_tecnica_tipo_equipo ADD CONSTRAINT "FK_verificacion_tecnica_tipo_equipo_tipo_equipo"
	FOREIGN KEY (k_id_tipo_equipo) REFERENCES tipo_equipo (k_id_tipo_equipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE verificacion_tecnica_tipo_equipo ADD CONSTRAINT "FK_verificacion_tecnica_tipo_equipo_verificacion_tecnica"
	FOREIGN KEY (k_id_verificacion) REFERENCES verificacion_tecnica (k_id_verificacion) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE area_servicio
	IS 'Esta tabla es la encargada de guardar todas aquellas áreas de trabajo que pertenecen a las sedes del cliente.'
;

COMMENT ON COLUMN area_servicio.k_id_area_servicio
	IS 'ID que se le asigna dentro de la empresa al area de servicio '
;

COMMENT ON COLUMN area_servicio.n_nombre_area
	IS 'Nombre unico con el que se identifica el area de servicio'
;

COMMENT ON COLUMN area_servicio.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN area_servicio.k_id_sede
	IS 'ID de la sede donde se esta prestando el area del servicio'
;

COMMENT ON TABLE ciudad
	IS 'Tabla encargada de guardar la ciudades'
;

COMMENT ON COLUMN ciudad.k_id_ciudad
	IS 'PK de la ciudad.'
;

COMMENT ON COLUMN ciudad.n_nombre_ciudad
	IS 'Nombre de la ciudad.'
;

COMMENT ON COLUMN ciudad.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN ciudad.k_id_pais
	IS 'FK que viene desde pais.'
;

COMMENT ON TABLE cliente
	IS 'Esta es la tabla encargada de guardar a todos los clientes.'
;

COMMENT ON COLUMN cliente.k_id_cliente
	IS 'iD (NIT juridico, NIT natural, CC) unico con el que se identifica al cliente.'
;

COMMENT ON COLUMN cliente.n_tipo_identificacion
	IS 'Tipo de documento, este puede ser cedula de ciudadania, cedula extrangera, entre otras '
;

COMMENT ON COLUMN cliente.n_razon_social
	IS 'Razon social a la que pertenece al cliente.'
;

COMMENT ON COLUMN cliente.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN cliente.k_id_pais
	IS 'ID unico del pais de donde proviene el usuario '
;

COMMENT ON TABLE correo_cliente
	IS 'Esta es la tabla encargada de guardar los correos electrónicos que pertenecen a los clientes.'
;

COMMENT ON COLUMN correo_cliente.k_id_correo_cliente
	IS 'Este es el PK que representa la los correo_cliente.'
;

COMMENT ON COLUMN correo_cliente.n_correo_cliente
	IS 'Informacion de contacto del cliente. El correo tiene ciertas especificaciones '
;

COMMENT ON COLUMN correo_cliente.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN correo_cliente.k_id_cliente
	IS 'ID del cliente con el que esta relacionado el correo electronico '
;

COMMENT ON TABLE correo_persona
	IS 'Esta tabla será la encargada de almacenar los correos electrónicos de las personas.'
;

COMMENT ON COLUMN correo_persona.k_id_correo_persona
	IS 'Llave primaria de la tabla correo_persona.'
;

COMMENT ON COLUMN correo_persona.n_correo_persona
	IS 'Corresponde al correo electrónico de la persona.'
;

COMMENT ON COLUMN correo_persona.k_identificador
	IS 'Es la llave foránea que referencia a la tabla persona.'
;

COMMENT ON COLUMN correo_persona.b_estado_acitivo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON TABLE dato_metrologico
	IS 'Esta tabla es la encargada de guardar las verificaciones metrologicas que se le hace a cada tipo de equipo.'
;

COMMENT ON COLUMN dato_metrologico.d_valor
	IS 'Es el valor de valor de verificación predeterminada.'
;

COMMENT ON COLUMN dato_metrologico.n_tipo
	IS 'Este es el tipo de valor que se va a verificar (kg, %...)'
;

COMMENT ON COLUMN dato_metrologico.k_id_tipo_equipo
	IS 'FK que viene desde tipo_equipo.'
;

COMMENT ON TABLE encargado
	IS 'Esta es la tabla encargada de almacenar a todos los encargados de las sedes y áreas de trabajo de los clientes.'
;

COMMENT ON COLUMN encargado.k_identificador
	IS 'Esta es la FK que viene desde la persona.'
;

COMMENT ON COLUMN encargado.t_tipo_encargado
	IS 'Esta columna es la encargada de guardar el tipo de encargado que es.'
;

COMMENT ON COLUMN encargado.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN encargado.k_id_area_servicio
	IS 'Esta es la FK que viene desde el area de servicio.'
;

COMMENT ON COLUMN encargado.k_id_sede
	IS 'Esta es la FK que viene desde la sede.'
;

COMMENT ON TABLE equipo
	IS 'Esta es la tabla encargada de relacionar la marca y el tipos de equipo.'
;

COMMENT ON COLUMN equipo.k_id_equipo
	IS 'PK que diferencia a los equipo.'
;

COMMENT ON COLUMN equipo.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN equipo.k_id_tipo_equipo
	IS 'FK que viene desde el tipo_equipo.'
;

COMMENT ON COLUMN equipo.k_id_marca
	IS 'Fk que viene desde la marca.'
;

COMMENT ON TABLE equipo_cliente
	IS 'Esta es la tabla encargada de guardar los equipo que le pertenecen a cada cliente.'
;

COMMENT ON COLUMN equipo_cliente.k_id_equipo_cliente
	IS 'PK que diferencia a los equipos que pertenecen al cliente.'
;

COMMENT ON COLUMN equipo_cliente.k_serie
	IS 'Numero de serie que pertenece al equipo.'
;

COMMENT ON COLUMN equipo_cliente.f_fecha_compra
	IS 'Fecha en la que el cliente compra el equipo.'
;

COMMENT ON COLUMN equipo_cliente.v_valor_compra
	IS 'Precio que tuvo que pagar el cliente para tener el equipo.'
;

COMMENT ON COLUMN equipo_cliente.n_no_inventario
	IS 'Numero de inventario que da el cliente a su equipo.'
;

COMMENT ON COLUMN equipo_cliente.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN equipo_cliente.k_id_area_servicio
	IS 'ID del area del servicio el cual otorga el equipo a cliente.'
;

COMMENT ON COLUMN equipo_cliente.k_id_modelo
	IS 'FK que viene desde el modelo.'
;

COMMENT ON TABLE fabricante
	IS 'Tabla encargada de guardar a los distintos fabricante.'
;

COMMENT ON COLUMN fabricante.k_id_fabricante
	IS 'PK con el que se identifica el fabricante dentro de la empresa.'
;

COMMENT ON COLUMN fabricante.n_nombre_fabricante
	IS 'Nombre del fabricante.'
;

COMMENT ON COLUMN fabricante.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN fabricante.k_id_pais
	IS 'FK del pais de donde proviene el fabricante.'
;

COMMENT ON TABLE marca
	IS 'Tabla encargada de guardar las marcas de los equipos.'
;

COMMENT ON COLUMN marca.k_id_marca
	IS 'PK de la marca del equipo.'
;

COMMENT ON COLUMN marca.n_nombre_marca
	IS 'Nombre de la marca que tiene cada uno de los equipos.'
;

COMMENT ON COLUMN marca.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON TABLE modelo
	IS 'Esta es la tabla encargada de guardar el modelo de los equipos.'
;

COMMENT ON COLUMN modelo.k_id_modelo
	IS 'PK del modelo del equipo '
;

COMMENT ON COLUMN modelo.n_invima
	IS 'Registro invima con el que se encuentra relacionado con el modelo '
;

COMMENT ON COLUMN modelo.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN modelo.k_id_fabricante
	IS 'ID del fabricante que ha producido el modelo del equipo'
;

COMMENT ON COLUMN modelo.k_id_equipo
	IS 'FK que vien desde el equipo'
;

COMMENT ON TABLE orden_trabajo
	IS 'Esta tabla se encarga de almacenar todas las órdenes de trabajo que serán generadas y ejecutadas.'
;

COMMENT ON COLUMN orden_trabajo.k_id_orden_trabajo
	IS 'Llave primaria de la tabla orden_trabajo.'
;

COMMENT ON COLUMN orden_trabajo.f_fecha_mantenimiento
	IS 'Esta columna se encargará de guardar la fecha en la que se creó la orden de trabajo.'
;

COMMENT ON COLUMN orden_trabajo.n_periodicidad
	IS 'Este campo guardará la periodicidad de la orden de trabajo (cada cuánto se les realiza mantenimiento a estos equipos).'
;

COMMENT ON COLUMN orden_trabajo.k_identificador
	IS 'Este campo es la FK la persona que representa al ingeniero encargado de la orden de trabajo.'
;

COMMENT ON COLUMN orden_trabajo.t_estado_ejecucion
	IS 'Este campo es el encargado de reflejar el estado de ejecución de la orden de trabajo (CREADO, EJECUCION, EJECUTADO).'
;

COMMENT ON COLUMN orden_trabajo.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON TABLE pais
	IS 'Esta es la tabla encargada de guardar a los pais'
;

COMMENT ON COLUMN pais.k_id_pais
	IS 'ID del pais de donde proviene un fabricante o un cliente '
;

COMMENT ON COLUMN pais.n_nombre_pais
	IS 'nombre del pais de donde puede provenir un fabricante o un cliente '
;

COMMENT ON COLUMN pais.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON TABLE persona
	IS 'Esta tabla se encarga de almacenar todas las personas necesarias para la ejecución de los casos de uso de la aplicación.'
;

COMMENT ON COLUMN persona.k_identificador
	IS 'ID que se le otorga a la persona de manera interna dentro de la empresa '
;

COMMENT ON COLUMN persona.k_cedula
	IS 'Cédula de la persona utilizada como identificador único.'
;

COMMENT ON COLUMN persona.n_primer_nombre
	IS 'Primer nombre de la persona.'
;

COMMENT ON COLUMN persona.n_segundo_nombre
	IS 'Segundo nombre de la persona.'
;

COMMENT ON COLUMN persona.n_primer_apellido
	IS 'Primer apellido de la persona.'
;

COMMENT ON COLUMN persona.n_segundo_apellido
	IS 'Segundo apellido de la persona.'
;

COMMENT ON COLUMN persona.t_tipo_persona
	IS 'Tipo de persona que sera (ingeniero, encargado, representante legal)'
;

COMMENT ON COLUMN persona.t_segundo_tipo_persona
	IS 'Tipo de persona que sera (encargado, representante legal)'
;

COMMENT ON COLUMN persona.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON TABLE reporte_servicio
	IS 'Esta tabla se encarga de almacenar los reportes de servicio realizados a cada equipo durante la orden de trabajo.'
;

COMMENT ON COLUMN reporte_servicio.k_id_reporte_servicio
	IS 'Es la llave primaria que actúa como identificador único de los reportes de servicio.'
;

COMMENT ON COLUMN reporte_servicio.k_id_orden_trabajo
	IS 'Es la llave foránea que referencia a la tabla orden_de_trabajo.'
;

COMMENT ON COLUMN reporte_servicio.k_id_equipo_cliente
	IS 'Es la llave foránea que referencia a la tabla equipo_cliente.'
;

COMMENT ON COLUMN reporte_servicio.k_id_cliente
	IS 'Es la llave foránea que referencia a la tabla cliente.'
;

COMMENT ON TABLE representante_legal
	IS 'Esta tabla actúa como una relación intermedia entre las tablas persona y cliente, permitiendo asignar representantes legales a los clientes.'
;

COMMENT ON COLUMN representante_legal.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN representante_legal.k_identificador
	IS 'FK proveniente de la tabla persona.'
;

COMMENT ON COLUMN representante_legal.k_id_cliente
	IS ' FK proveniente de la clave cliente.'
;

COMMENT ON TABLE sede
	IS 'Esta tabla es la encargada de guardar las sedes que le pertenecen al cliente.'
;

COMMENT ON COLUMN sede.k_id_sede
	IS 'ID con el que se identifica la sede dentro de la empresa.'
;

COMMENT ON COLUMN sede.n_nombre_sede
	IS 'Nombre de la sede.'
;

COMMENT ON COLUMN sede.dir_calle
	IS 'Parte de la dirección que pertenece a la calle.'
;

COMMENT ON COLUMN sede.dir_carrera
	IS 'Parte de la dirección que pertenece a la carrera.'
;

COMMENT ON COLUMN sede.dir_num
	IS 'Parte de la dirección que pertenece al numero.'
;

COMMENT ON COLUMN sede.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN sede.k_id_cliente
	IS 'FK que viene desde el cliente que representa al dueño de la sede.'
;

COMMENT ON COLUMN sede.k_id_ciudad
	IS 'ID de la ciudad en donde se encuentra la sede '
;

COMMENT ON TABLE telefono_cliente
	IS 'Esta tabla es la encargada de guardar los telefonos que pertenecen al cliente.'
;

COMMENT ON COLUMN telefono_cliente.k_id_telefono_cliente
	IS 'Esta es la PK que identifica a los telefono_cliente.'
;

COMMENT ON COLUMN telefono_cliente.n_telefono_cliente
	IS 'Número telefonico del cliente '
;

COMMENT ON COLUMN telefono_cliente.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN telefono_cliente.k_id_cliente
	IS 'ID del cliente del cual esta relacionado el numero telefonico '
;

COMMENT ON TABLE telefono_persona
	IS 'Esta tabla se encarga de almacenar los números de teléfono asociados a las personas.'
;

COMMENT ON COLUMN telefono_persona.k_id_telefono_persona
	IS 'Llave primaria de la tabla telefono_persona.'
;

COMMENT ON COLUMN telefono_persona.n_telefono_persona
	IS 'Este es el número de teléfono de la persona.'
;

COMMENT ON COLUMN telefono_persona.k_identificador
	IS 'Es la llave foránea que referencia a la tabla persona.'
;

COMMENT ON COLUMN telefono_persona.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON TABLE tipo_equipo
	IS 'Esta es la tabla encargada de guardar todo los tipo_equipo.'
;

COMMENT ON COLUMN tipo_equipo.k_id_tipo_equipo
	IS 'PK del tipo de equipo.'
;

COMMENT ON COLUMN tipo_equipo.n_nombre_tipo_equipo
	IS 'Nombre del tipo de equipo '
;

COMMENT ON COLUMN tipo_equipo.t_definicion_tecnica
	IS 'Definicion tecnica del tipo de equipo, en donde se especifica las caracteristicas que tiene este '
;

COMMENT ON COLUMN tipo_equipo.t_recomendaciones_cuidado
	IS 'Esta columna es la encargado de guardar las recomendaciones de cuidado del tipo_equipo.'
;

COMMENT ON COLUMN tipo_equipo.i_voltage
	IS 'Voltage que tiene cada uno de los diferentes equipos'
;

COMMENT ON COLUMN tipo_equipo.d_amperaje
	IS 'Amperaje que tiene cada uno de los diferentes equipos'
;

COMMENT ON COLUMN tipo_equipo.t_tecnologia_predominante
	IS 'Tecnologia predominante que actua en el tipo de equipo '
;

COMMENT ON COLUMN tipo_equipo.b_verificable
	IS 'Esta columan es la encargada de guardar si a este tipo equipo se le hace verificaión metrologica o no.'
;

COMMENT ON COLUMN tipo_equipo.m_valor_unitario_mantenimiento
	IS 'Este es el valor que tendra el matenimiento del tipo_equipo.'
;

COMMENT ON COLUMN tipo_equipo.n_tipo_verificacion
	IS 'Aqui se va a determinar la modalidad de verificación metrologica.'
;

COMMENT ON COLUMN tipo_equipo.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON TABLE verificacion_metrologica
	IS 'Esta tabla se encarga de almacenar las verificaciones metrológicas realizadas a cada equipo durante el mantenimiento.'
;

COMMENT ON COLUMN verificacion_metrologica.d_valor_equipo
	IS 'Este corresponde al valor registrado en la verificación realizada al equipo.'
;

COMMENT ON COLUMN verificacion_metrologica.d_valor_patron
	IS 'Este corresponde al valor registrado del equipo patrón durante la verificación realizada al equipo.'
;

COMMENT ON COLUMN verificacion_metrologica.k_id_reporte_servicio
	IS 'Es la llave foránea que referencia a la tabla reporte_servicio.'
;

COMMENT ON TABLE verificacion_tecnica
	IS 'Esta es la tabla encargada de guardar las distintas verificacion_metrologica de los equipos.'
;

COMMENT ON COLUMN verificacion_tecnica.k_id_verificacion
	IS 'PK de que diferencia a los distintos verificacion_tecnica.'
;

COMMENT ON COLUMN verificacion_tecnica.t_descripcion
	IS 'Descripcion de la verificacion_metrologica.'
;

COMMENT ON COLUMN verificacion_tecnica.t_tipo_verificacion
	IS 'Esta columna es la encargada de guardar el tipo de verificacion_metrologica.'
;

COMMENT ON COLUMN verificacion_tecnica.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON TABLE verificacion_tecnica_tipo_equipo
	IS 'Esta es la tabla que servira para poder relacionar el tipo_equipo con verificacion_metrologica.'
;

COMMENT ON COLUMN verificacion_tecnica_tipo_equipo.k_id_verificacion
	IS 'FK que viene desde verificacion_metrologica'
;

COMMENT ON COLUMN verificacion_tecnica_tipo_equipo.b_estado_activo
	IS 'Esta columna se encarga de indicar si el dato está activo o no, permitiendo conservar el historial de la base de datos sin necesidad de eliminar registros.'
;

COMMENT ON COLUMN verificacion_tecnica_tipo_equipo.k_id_tipo_equipo
	IS 'FK que viene desde tipo_equipo.'
;
