/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 10-may.-2026 10:20:10 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS area_servicio CASCADE
;

DROP TABLE IF EXISTS ciudad CASCADE
;

DROP TABLE IF EXISTS cliente CASCADE
;

DROP TABLE IF EXISTS contrato CASCADE
;

DROP TABLE IF EXISTS correo_cliente CASCADE
;

DROP TABLE IF EXISTS correo_persona CASCADE
;

DROP TABLE IF EXISTS cotizacion CASCADE
;

DROP TABLE IF EXISTS dato_metrologico CASCADE
;

DROP TABLE IF EXISTS encargado CASCADE
;

DROP TABLE IF EXISTS equipo CASCADE
;

DROP TABLE IF EXISTS equipo_cliente CASCADE
;

DROP TABLE IF EXISTS fabricante CASCADE
;

DROP TABLE IF EXISTS marca CASCADE
;

DROP TABLE IF EXISTS modelo CASCADE
;

DROP TABLE IF EXISTS orden_trabajo CASCADE
;

DROP TABLE IF EXISTS pais CASCADE
;

DROP TABLE IF EXISTS persona CASCADE
;

DROP TABLE IF EXISTS protocolo_mantenimiento CASCADE
;

DROP TABLE IF EXISTS reporte_servicio CASCADE
;

DROP TABLE IF EXISTS reporte_servicio_snapshot CASCADE
;

DROP TABLE IF EXISTS representante_legal CASCADE
;

DROP TABLE IF EXISTS sede CASCADE
;

DROP TABLE IF EXISTS telefono_cliente CASCADE
;

DROP TABLE IF EXISTS telefono_persona CASCADE
;

DROP TABLE IF EXISTS tipo_equipo CASCADE
;

DROP TABLE IF EXISTS verificacion_ingreso CASCADE
;

DROP TABLE IF EXISTS verificacion_metrologica CASCADE
;

DROP TABLE IF EXISTS verificacion_tecnica CASCADE
;

DROP TABLE IF EXISTS verificacion_tecnica_tipo_equipo CASCADE
;

/* Create Tables */

CREATE TABLE area_servicio
(
	k_id_area_servicio uuid NOT NULL,	-- ID que se le asigna dentro de la empresa al area de servicio 
	n_nombre_area varchar(50) NULL,	-- Nombre unico con el que se identifica el area de servicio
	k_id_sede uuid NULL	-- ID de la sede donde se esta prestando el area del servicio
)
;

CREATE TABLE ciudad
(
	k_id_ciudad varchar(10) NOT NULL,	-- ID de la ciudad 
	n_nombre_ciudad varchar(50) NOT NULL,	-- nombre de la ciudad 
	k_id_pais varchar(3) NULL
)
;

CREATE TABLE cliente
(
	k_id_cliente varchar(11) NOT NULL,	-- ID unico con el que se identifica el usuario 
	n_tipo_identificacion varchar(12) NOT NULL,	-- Tipo de documento, este puede ser cedula de ciudadania, cedula extrangera, entre otras 
	n_razon_social varchar(50) NOT NULL,	-- Razon social a la que pertenece el usuario 
	n_tipo_cliente varchar(50) NOT NULL,	-- ID con el que se identifica el cliente de manera interna en la empresa 
	k_id_pais varchar(3) NULL	-- ID unico del pais de donde proviene el usuario 
)
;

CREATE TABLE contrato
(
	k_id_contrato varchar(10) NOT NULL,
	t_estado_contrato varchar(20) NOT NULL,
	f_fecha_inicio date NOT NULL,
	f_fecha_finalizacion date NULL,
	t_observaciones varchar(50) NULL
)
;

CREATE TABLE correo_cliente
(
	k_id_correo_cliente uuid NOT NULL,
	n_correo_cliente varchar(50) NOT NULL,	-- Informacion de contacto del cliente. El correo tiene ciertas especificaciones 
	k_id_cliente varchar(11) NULL	-- ID del cliente con el que esta relacionado el correo electronico 
)
;

CREATE TABLE correo_persona
(
	k_id_correo_persona uuid NOT NULL,
	n_correo_persona varchar(50) NOT NULL,	-- Corresponde al correo electrónico de la persona.
	k_identificador uuid NULL	-- Es la llave foránea que referencia a la tabla persona.
)
;

CREATE TABLE cotizacion
(
	k_id_equipo_cliente uuid NOT NULL,
	k_id_contrato varchar(10) NULL,
	m_valor_unitario_mantenimiento bigint NOT NULL,
	m_valor_total bigint NOT NULL,
	t_observacion varchar(250) NULL,
	f_fecha_emision date NOT NULL,
	f_validez date NOT NULL,
	t_estado_cotizacion varchar(20) NOT NULL
)
;

CREATE TABLE dato_metrologico
(
	d_valor numeric(10,4) NOT NULL,
	n_tipo varchar(50) NOT NULL,
	k_id_tipo_equipo uuid NULL
)
;

CREATE TABLE encargado
(
	k_identificador uuid NOT NULL,
	t_tipo_encargado varchar(16) NOT NULL,
	k_id_area_servicio uuid NULL,
	k_id_sede uuid NULL
)
;

CREATE TABLE equipo
(
	k_id_equipo uuid NOT NULL,
	k_id_tipo_equipo uuid NOT NULL,
	k_id_marca uuid NOT NULL
)
;

CREATE TABLE equipo_cliente
(
	k_id_equipo_cliente uuid NOT NULL,
	k_serie varchar(50) NOT NULL,
	f_fecha_compra date NULL,	-- Fecha en la que el cliente compra el equipo 
	v_valor_compra bigint NULL,	-- Precio que tuvo que pagar el cliente para tener el equipo
	n_no_inventario varchar(50) NULL,	-- Numero de inventario
	k_id_area_servicio uuid NULL,	-- ID del area del servicio el cual otorga el equipo a cliente
	k_id_modelo uuid NULL
)
;

CREATE TABLE fabricante
(
	k_id_fabricante uuid NOT NULL,	-- ID con el que se identifica el fabricante dentro de la empresa 
	n_nombre_fabricante varchar(50) NOT NULL,	-- nombre del fabricante 
	k_id_pais varchar(3) NULL	-- ID del pais de donde proviene el fabricante 
)
;

CREATE TABLE marca
(
	k_id_marca uuid NOT NULL,	-- ID de la marca del equipo
	n_nombre_marca varchar(50) NULL	-- Nombre de la marca que tiene cada uno de los equipos
)
;

CREATE TABLE modelo
(
	k_id_modelo uuid NOT NULL,	-- ID del modelo del equipo 
	n_invima varchar(50) NULL,	-- Registro invima con el que se encuentra relacionado con el modelo 
	k_id_fabricante uuid NULL,	-- ID del fabricante que ha producido el modelo del equipo
	k_id_equipo uuid NULL
)
;

CREATE TABLE orden_trabajo
(
	k_id_orden_trabajo uuid NOT NULL,
	f_fecha_mantenimiento timestamp without time zone NOT NULL,
	n_periodicidad varchar(15) NOT NULL,
	k_identificador uuid NULL
)
;

CREATE TABLE pais
(
	k_id_pais varchar(3) NOT NULL,	-- ID del pais de donde proviene un fabricante o un cliente 
	n_nombre_pais varchar(20) NOT NULL	-- nombre del pais de donde puede provenir un fabricante o un cliente 
)
;

CREATE TABLE persona
(
	k_identificador uuid NOT NULL,	-- ID que se le otorga a la persona de manera interna dentro de la empresa 
	k_cedula varchar(10) NOT NULL,	-- Cedula del supervisor del cliente 
	n_primer_nombre varchar(50) NOT NULL,
	n_segundo_nombre varchar(50) NULL,
	n_primer_apellido varchar(50) NOT NULL,
	n_segundo_apellido varchar(50) NULL,
	t_tipo_persona varchar(19) NOT NULL,
	t_segundo_tipo_persona varchar(19) NULL
)
;

CREATE TABLE protocolo_mantenimiento
(
	k_id_verificacion uuid NOT NULL,
	b_ejecucion_protocolo boolean NOT NULL   DEFAULT false,
	k_id_reporte_servicio uuid NULL
)
;

CREATE TABLE reporte_servicio
(
	k_id_reporte_servicio uuid NOT NULL,	-- Es la llave primaria que actúa como identificador único de los reportes de servicio.
	k_id_orden_trabajo varchar(10) NOT NULL,	-- Es la llave foránea que referencia a la tabla orden_de_trabajo.
	k_id_equipo_cliente varchar(10) NOT NULL,	-- Es la llave foránea que referencia a la tabla equipo_cliente.
	k_id_cliente uuid NOT NULL,	-- Es la llave foránea que referencia a la tabla cliente.
	t_observaciones_reporte_servico varchar(250) NULL,
	d_valor_equipo numeric(10,4) NULL,
	d_valor_patron numeric(10,4) NULL,
	t_resultado_verificacion_tecnica varchar(50) NULL
)
;

CREATE TABLE reporte_servicio_snapshot
(
	k_id_reporte_snapshot uuid NOT NULL,
	t_creado timestamp without time zone NOT NULL,
	s_snapshot JSONB NOT NULL
)
;

CREATE TABLE representante_legal
(
	k_identificador uuid NOT NULL,
	k_id_cliente varchar(11) NOT NULL
)
;

CREATE TABLE sede
(
	k_id_sede uuid NOT NULL,	-- ID con el que se identifica la sede dentro de la empresa
	n_nombre_sede varchar(50) NOT NULL,	-- nombre de la sede
	dir_calle varchar(50) NOT NULL,
	dir_carrera varchar(50) NOT NULL,
	dir_num varchar(50) NOT NULL,
	k_id_cliente varchar(11) NULL,	-- Numero de identificacion de las personas que se encuentran en la sede 
	k_id_ciudad varchar(10) NULL	-- ID de la ciudad en donde se encuentra la sede 
)
;

CREATE TABLE telefono_cliente
(
	k_id_telefono_cliente uuid NOT NULL,
	n_telefono_cliente varchar(50) NOT NULL,	-- Número telefonico del cliente 
	k_id_cliente varchar(11) NULL	-- ID del cliente del cual esta relacionado el numero telefonico 
)
;

CREATE TABLE telefono_persona
(
	k_id_telefono_persona uuid NOT NULL,
	n_telefono_persona varchar(10) NOT NULL,	-- Este es el número de teléfono de la persona.
	k_identificador uuid NULL	-- Es la llave foránea que referencia a la tabla persona.
)
;

CREATE TABLE tipo_equipo
(
	k_id_tipo_equipo uuid NOT NULL,	-- ID del tipo de equipo
	n_nombre_tipo_equipo varchar(50) NOT NULL,	-- Nombre del tipo de equipo 
	t_definicion_tecnica varchar(250) NOT NULL,	-- Definicion tecnica del tipo de equipo, en donde se especifica las caracteristicas que tiene este 
	t_recomendaciones_cuidado varchar(250) NOT NULL,
	i_voltage integer NULL,	-- Voltage que tiene cada uno de los diferentes equipos
	d_amperaje numeric(2) NULL,	-- Voltage que tiene cada uno de los diferentes equipos
	t_tecnologia_predominante varchar(50) NOT NULL,	-- Tecnologia predominante que actua en el tipo de equipo 
	b_verificable boolean NOT NULL,
	m_valor_unitario_mantenimiento bigint NOT NULL,
	n_tipo_verificacion varchar(50) NULL
)
;

CREATE TABLE verificacion_ingreso
(
	k_id_verificacion uuid NOT NULL,
	b_aplica boolean NOT NULL   DEFAULT false,
	b_conformidad_ingreso boolean NOT NULL   DEFAULT false,
	t_observacion_ingreso varchar(250) NULL,
	k_id_reporte_servicio uuid NULL
)
;

CREATE TABLE verificacion_metrologica
(
	d_valor_equipo numeric(10,4) NOT NULL,	-- Este corresponde al valor registrado en la verificación realizada al equipo.
	d_valor_patron numeric(10,4) NOT NULL,	-- Este corresponde al valor registrado del equipo patrón durante la verificación realizada al equipo.
	k_id_reporte_servicio uuid NULL	-- Es la llave foránea que referencia a la tabla reporte_servicio.
)
;

CREATE TABLE verificacion_tecnica
(
	k_id_verificacion uuid NOT NULL,
	t_descripcion varchar(250) NOT NULL,
	t_tipo_verificacion varchar(25) NOT NULL
)
;

CREATE TABLE verificacion_tecnica_tipo_equipo
(
	k_id_verificacion uuid NOT NULL,
	k_id_tipo_equipo uuid NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE area_servicio ADD CONSTRAINT "PK_area_servicio"
	PRIMARY KEY (k_id_area_servicio)
;

CREATE INDEX "IXFK_area_servicio_sede" ON area_servicio (k_id_sede ASC)
;

ALTER TABLE ciudad ADD CONSTRAINT "PK_ciudad"
	PRIMARY KEY (k_id_ciudad)
;

CREATE INDEX "IXFK_ciudad_pais" ON ciudad (k_id_pais ASC)
;

ALTER TABLE cliente ADD CONSTRAINT "PK_cliente"
	PRIMARY KEY (k_id_cliente)
;

ALTER TABLE cliente ADD CONSTRAINT "CHK_tipo_identifiacion" CHECK (n_tipo_identificacion IN ('NIT_juridico', 'NIT_natural', 'CC', 'CE'))
;

CREATE INDEX "IXFK_cliente_pais" ON cliente (k_id_pais ASC)
;

ALTER TABLE contrato ADD CONSTRAINT "PK_contrato"
	PRIMARY KEY (k_id_contrato)
;

ALTER TABLE contrato ADD CONSTRAINT "CHK_estado_contrato" CHECK (t_estado_contrato IN (
    'borrador',
    'en_revision',
    'aprobado',
    'firmado',
    'activo',
    'suspendido',
    'renovado',
    'vencido',
    'cancelado',
    'rescindido',
    'finalizado'
  ))
;

ALTER TABLE correo_cliente ADD CONSTRAINT "PK_correo_cliente"
	PRIMARY KEY (k_id_correo_cliente)
;

CREATE INDEX "IXFK_correo_cliente_cliente" ON correo_cliente (k_id_cliente ASC)
;

ALTER TABLE correo_persona ADD CONSTRAINT "PK_correo_persona"
	PRIMARY KEY (k_id_correo_persona)
;

CREATE INDEX "IXFK_correo_persona" ON correo_persona (k_identificador ASC)
;

ALTER TABLE cotizacion ADD CONSTRAINT "PK_cotizacin"
	PRIMARY KEY (k_id_equipo_cliente)
;

ALTER TABLE cotizacion ADD CONSTRAINT "CHK_estado_cotizacion" CHECK (t_estado_cotizacion IN (
    'borrador',
    'enviada',
    'aprobada',
    'rechazada',
    'vencida',
    'cancelada',
    'convertida_contrato'
  ))
;

CREATE INDEX "IXFK_cotizacion_contrato" ON cotizacion (k_id_contrato ASC)
;

CREATE INDEX "IXFK_cotizacion_equipo_cliente" ON cotizacion (k_id_equipo_cliente ASC)
;

CREATE INDEX "IXFK_dato_metrologico_tipo_equipo" ON dato_metrologico (k_id_tipo_equipo ASC)
;

ALTER TABLE encargado ADD CONSTRAINT "PK_encargado"
	PRIMARY KEY (k_identificador)
;

ALTER TABLE encargado ADD CONSTRAINT "CHK_tipo_encagado" CHECK (t_tipo_encargado IN ('sede', 'area_servicio'))
;

CREATE INDEX "IXFK_encargado_area_servicio" ON encargado (k_id_area_servicio ASC)
;

CREATE INDEX "IXFK_encargado_persona" ON encargado (k_identificador ASC)
;

CREATE INDEX "IXFK_encargado_sede" ON encargado (k_id_sede ASC)
;

ALTER TABLE equipo ADD CONSTRAINT "PK_equipo"
	PRIMARY KEY (k_id_equipo)
;

CREATE INDEX "IXFK_equipo_marca" ON equipo (k_id_marca ASC)
;

CREATE INDEX "IXFK_equipo_tipo_equipo" ON equipo (k_id_tipo_equipo ASC)
;

ALTER TABLE equipo_cliente ADD CONSTRAINT "PK_equipo_cliente"
	PRIMARY KEY (k_id_equipo_cliente)
;

CREATE INDEX "IXFK_equipo_cliente_area_servicio" ON equipo_cliente (k_id_area_servicio ASC)
;

CREATE INDEX "IXFK_equipo_cliente_modelo" ON equipo_cliente (k_id_modelo ASC)
;

ALTER TABLE fabricante ADD CONSTRAINT "PK_fabricante"
	PRIMARY KEY (k_id_fabricante)
;

CREATE INDEX "IXFK_fabricante_pais" ON fabricante (k_id_pais ASC)
;

ALTER TABLE marca ADD CONSTRAINT "PK_marca"
	PRIMARY KEY (k_id_marca)
;

ALTER TABLE modelo ADD CONSTRAINT "PK_modelo"
	PRIMARY KEY (k_id_modelo)
;

CREATE INDEX "IXFK_modelo_equipo" ON modelo (k_id_equipo ASC)
;

CREATE INDEX "IXFK_modelo_fabricante" ON modelo (k_id_fabricante ASC)
;

ALTER TABLE orden_trabajo ADD CONSTRAINT "PK_mantenimiento"
	PRIMARY KEY (k_id_orden_trabajo)
;

ALTER TABLE orden_trabajo ADD CONSTRAINT "CHK_periodicidad" CHECK (n_periodicidad IN ('mensual', 'trimestral', 'semestral', 'anual'))
;

CREATE INDEX "IXFK_orden_trabajo_persona" ON orden_trabajo (k_identificador ASC)
;

ALTER TABLE pais ADD CONSTRAINT "PK_pais"
	PRIMARY KEY (k_id_pais)
;

ALTER TABLE persona ADD CONSTRAINT "PK_persona"
	PRIMARY KEY (k_identificador)
;

ALTER TABLE persona 
  ADD CONSTRAINT "UQ_cedula" UNIQUE (k_cedula)
;

ALTER TABLE persona ADD CONSTRAINT "CHK_tipo_persona" CHECK (t_tipo_persona IN ('ingeniero', 'encargado', 'representante_legal') AND
t_segundo_tipo_persona IN ('encargado', 'representante_legal'))
;

-- Primero, crea la función que contiene la lógica
CREATE OR REPLACE FUNCTION validar_roles_persona()
RETURNS TRIGGER AS $$
BEGIN
    -- Regla 1: Si t_tipo_persona es 'ingeniero', no se puede llenar t_segundo_tipo_persona
    IF NEW.t_tipo_persona = 'ingeniero' AND NEW.t_segundo_tipo_persona IS NOT NULL THEN
        RAISE EXCEPTION 'Si t_tipo_persona es "ingeniero", t_segundo_tipo_persona debe ser NULL.';
    END IF;

    -- Regla 2: Si ambos están llenos, no pueden ser iguales
    IF NEW.t_segundo_tipo_persona IS NOT NULL AND NEW.t_tipo_persona = NEW.t_segundo_tipo_persona THEN
        RAISE EXCEPTION 't_tipo_persona y t_segundo_tipo_persona no pueden ser iguales.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
;

CREATE INDEX "IXFK_protocolo_mantenimiento_reporte_servicio" ON protocolo_mantenimiento (k_id_reporte_servicio ASC)
;

ALTER TABLE reporte_servicio ADD CONSTRAINT "PK_reporte_servicio"
	PRIMARY KEY (k_id_reporte_servicio)
;

ALTER TABLE reporte_servicio_snapshot ADD CONSTRAINT "PK_Table3"
	PRIMARY KEY (k_id_reporte_snapshot)
;

ALTER TABLE representante_legal ADD CONSTRAINT "PK_representante_legal"
	PRIMARY KEY (k_identificador,k_id_cliente)
;

CREATE INDEX "IXFK_representante_legal_cliente" ON representante_legal (k_id_cliente ASC)
;

CREATE INDEX "IXFK_representante_legal_persona" ON representante_legal (k_identificador ASC)
;

ALTER TABLE sede ADD CONSTRAINT "PK_sede"
	PRIMARY KEY (k_id_sede)
;

CREATE INDEX "IXFK_sede_ciudad" ON sede (k_id_ciudad ASC)
;

CREATE INDEX "IXFK_sede_cliente" ON sede (k_id_cliente ASC)
;

ALTER TABLE telefono_cliente ADD CONSTRAINT "PK_telefono_cliente"
	PRIMARY KEY (k_id_telefono_cliente)
;

CREATE INDEX "IXFK_telefono_cliente_cliente" ON telefono_cliente (k_id_cliente ASC)
;

ALTER TABLE telefono_persona ADD CONSTRAINT "PK_telefono_persona"
	PRIMARY KEY (k_id_telefono_persona)
;

CREATE INDEX "IXFK_telefono_persona" ON telefono_persona (k_identificador ASC)
;

ALTER TABLE tipo_equipo ADD CONSTRAINT "PK_TipeDeEquipo"
	PRIMARY KEY (k_id_tipo_equipo)
;

ALTER TABLE tipo_equipo ADD CONSTRAINT "CHK_tipo_verificacion" CHECK (n_tipo_verificacion IN ('patron_constante', 'equipo_constante', 'patron_equipo_variable'))
;

CREATE INDEX "IXFK_verificacion_ingreso_reporte_servicio" ON verificacion_ingreso (k_id_reporte_servicio ASC)
;

CREATE INDEX "IXFK_Verificacion metrologica_reporte_servicio" ON verificacion_metrologica (k_id_reporte_servicio ASC)
;

ALTER TABLE verificacion_tecnica ADD CONSTRAINT "PK_verificacion_tecnica"
	PRIMARY KEY (k_id_verificacion)
;

ALTER TABLE verificacion_tecnica ADD CONSTRAINT "CHK_tipo" CHECK (t_tipo_verificacion IN ('verificacion_tecnica_inicial', 'protocolo_mantenimiento'))
;

ALTER TABLE verificacion_tecnica_tipo_equipo ADD CONSTRAINT "PK_verificacion_tecnica_tipo_equipo"
	PRIMARY KEY (k_id_verificacion,k_id_tipo_equipo)
;

CREATE INDEX "IXFK_verificacion_tecnica_tipo_equipo_tipo_equipo" ON verificacion_tecnica_tipo_equipo (k_id_tipo_equipo ASC)
;

CREATE INDEX "IXFK_verificacion_tecnica_tipo_equipo_verificacion_tecnica" ON verificacion_tecnica_tipo_equipo (k_id_verificacion ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE area_servicio ADD CONSTRAINT "FK_area_servicio_sede"
	FOREIGN KEY (k_id_sede) REFERENCES sede (k_id_sede) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ciudad ADD CONSTRAINT "FK_ciudad_pais"
	FOREIGN KEY (k_id_pais) REFERENCES pais (k_id_pais) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cliente ADD CONSTRAINT "FK_cliente_pais"
	FOREIGN KEY (k_id_pais) REFERENCES pais (k_id_pais) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE correo_cliente ADD CONSTRAINT "FK_correo_cliente_cliente"
	FOREIGN KEY (k_id_cliente) REFERENCES cliente (k_id_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE correo_persona ADD CONSTRAINT "FK_correo_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cotizacion ADD CONSTRAINT "FK_cotizacion_contrato"
	FOREIGN KEY (k_id_contrato) REFERENCES contrato (k_id_contrato) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cotizacion ADD CONSTRAINT "FK_cotizacion_equipo_cliente"
	FOREIGN KEY (k_id_equipo_cliente) REFERENCES equipo_cliente (k_id_equipo_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dato_metrologico ADD CONSTRAINT "FK_dato_metrologico_tipo_equipo"
	FOREIGN KEY (k_id_tipo_equipo) REFERENCES tipo_equipo (k_id_tipo_equipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE encargado ADD CONSTRAINT "FK_encargado_area_servicio"
	FOREIGN KEY (k_id_area_servicio) REFERENCES area_servicio (k_id_area_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE encargado ADD CONSTRAINT "FK_encargado_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE encargado ADD CONSTRAINT "FK_encargado_sede"
	FOREIGN KEY (k_id_sede) REFERENCES sede (k_id_sede) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE equipo ADD CONSTRAINT "FK_equipo_marca"
	FOREIGN KEY (k_id_marca) REFERENCES marca (k_id_marca) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE equipo ADD CONSTRAINT "FK_equipo_tipo_equipo"
	FOREIGN KEY (k_id_tipo_equipo) REFERENCES tipo_equipo (k_id_tipo_equipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE equipo_cliente ADD CONSTRAINT "FK_equipo_cliente_area_servicio"
	FOREIGN KEY (k_id_area_servicio) REFERENCES area_servicio (k_id_area_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE equipo_cliente ADD CONSTRAINT "FK_equipo_cliente_modelo"
	FOREIGN KEY (k_id_modelo) REFERENCES modelo (k_id_modelo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE fabricante ADD CONSTRAINT "FK_fabricante_pais"
	FOREIGN KEY (k_id_pais) REFERENCES pais (k_id_pais) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE modelo ADD CONSTRAINT "FK_modelo_equipo"
	FOREIGN KEY (k_id_equipo) REFERENCES equipo (k_id_equipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE modelo ADD CONSTRAINT "FK_modelo_fabricante"
	FOREIGN KEY (k_id_fabricante) REFERENCES fabricante (k_id_fabricante) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE orden_trabajo ADD CONSTRAINT "FK_orden_trabajo_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE protocolo_mantenimiento ADD CONSTRAINT "FK_protocolo_mantenimiento_reporte_servicio"
	FOREIGN KEY (k_id_reporte_servicio) REFERENCES reporte_servicio (k_id_reporte_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE representante_legal ADD CONSTRAINT "FK_representante_legal_cliente"
	FOREIGN KEY (k_id_cliente) REFERENCES cliente (k_id_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE representante_legal ADD CONSTRAINT "FK_representante_legal_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sede ADD CONSTRAINT "FK_sede_ciudad"
	FOREIGN KEY (k_id_ciudad) REFERENCES ciudad (k_id_ciudad) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sede ADD CONSTRAINT "FK_sede_cliente"
	FOREIGN KEY (k_id_cliente) REFERENCES cliente (k_id_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE telefono_cliente ADD CONSTRAINT "FK_telefono_cliente_cliente"
	FOREIGN KEY (k_id_cliente) REFERENCES cliente (k_id_cliente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE telefono_persona ADD CONSTRAINT "FK_telefono_persona"
	FOREIGN KEY (k_identificador) REFERENCES persona (k_identificador) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE verificacion_ingreso ADD CONSTRAINT "FK_verificacion_ingreso_reporte_servicio"
	FOREIGN KEY (k_id_reporte_servicio) REFERENCES reporte_servicio (k_id_reporte_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE verificacion_metrologica ADD CONSTRAINT "FK_Verificacion metrologica_reporte_servicio"
	FOREIGN KEY (k_id_reporte_servicio) REFERENCES reporte_servicio (k_id_reporte_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE verificacion_tecnica_tipo_equipo ADD CONSTRAINT "FK_verificacion_tecnica_tipo_equipo_tipo_equipo"
	FOREIGN KEY (k_id_tipo_equipo) REFERENCES tipo_equipo (k_id_tipo_equipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE verificacion_tecnica_tipo_equipo ADD CONSTRAINT "FK_verificacion_tecnica_tipo_equipo_verificacion_tecnica"
	FOREIGN KEY (k_id_verificacion) REFERENCES verificacion_tecnica (k_id_verificacion) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN area_servicio.k_id_area_servicio
	IS 'ID que se le asigna dentro de la empresa al area de servicio '
;

COMMENT ON COLUMN area_servicio.n_nombre_area
	IS 'Nombre unico con el que se identifica el area de servicio'
;

COMMENT ON COLUMN area_servicio.k_id_sede
	IS 'ID de la sede donde se esta prestando el area del servicio'
;

COMMENT ON COLUMN ciudad.k_id_ciudad
	IS 'ID de la ciudad '
;

COMMENT ON COLUMN ciudad.n_nombre_ciudad
	IS 'nombre de la ciudad '
;

COMMENT ON COLUMN cliente.k_id_cliente
	IS 'ID unico con el que se identifica el usuario '
;

COMMENT ON COLUMN cliente.n_tipo_identificacion
	IS 'Tipo de documento, este puede ser cedula de ciudadania, cedula extrangera, entre otras '
;

COMMENT ON COLUMN cliente.n_razon_social
	IS 'Razon social a la que pertenece el usuario '
;

COMMENT ON COLUMN cliente.n_tipo_cliente
	IS 'ID con el que se identifica el cliente de manera interna en la empresa '
;

COMMENT ON COLUMN cliente.k_id_pais
	IS 'ID unico del pais de donde proviene el usuario '
;

COMMENT ON COLUMN correo_cliente.n_correo_cliente
	IS 'Informacion de contacto del cliente. El correo tiene ciertas especificaciones '
;

COMMENT ON COLUMN correo_cliente.k_id_cliente
	IS 'ID del cliente con el que esta relacionado el correo electronico '
;

COMMENT ON COLUMN correo_persona.n_correo_persona
	IS 'Corresponde al correo electrónico de la persona.'
;

COMMENT ON COLUMN correo_persona.k_identificador
	IS 'Es la llave foránea que referencia a la tabla persona.'
;

COMMENT ON COLUMN equipo_cliente.f_fecha_compra
	IS 'Fecha en la que el cliente compra el equipo '
;

COMMENT ON COLUMN equipo_cliente.v_valor_compra
	IS 'Precio que tuvo que pagar el cliente para tener el equipo'
;

COMMENT ON COLUMN equipo_cliente.n_no_inventario
	IS 'Numero de inventario'
;

COMMENT ON COLUMN equipo_cliente.k_id_area_servicio
	IS 'ID del area del servicio el cual otorga el equipo a cliente'
;

COMMENT ON COLUMN fabricante.k_id_fabricante
	IS 'ID con el que se identifica el fabricante dentro de la empresa '
;

COMMENT ON COLUMN fabricante.n_nombre_fabricante
	IS 'nombre del fabricante '
;

COMMENT ON COLUMN fabricante.k_id_pais
	IS 'ID del pais de donde proviene el fabricante '
;

COMMENT ON COLUMN marca.k_id_marca
	IS 'ID de la marca del equipo'
;

COMMENT ON COLUMN marca.n_nombre_marca
	IS 'Nombre de la marca que tiene cada uno de los equipos'
;

COMMENT ON COLUMN modelo.k_id_modelo
	IS 'ID del modelo del equipo '
;

COMMENT ON COLUMN modelo.n_invima
	IS 'Registro invima con el que se encuentra relacionado con el modelo '
;

COMMENT ON COLUMN modelo.k_id_fabricante
	IS 'ID del fabricante que ha producido el modelo del equipo'
;

COMMENT ON COLUMN pais.k_id_pais
	IS 'ID del pais de donde proviene un fabricante o un cliente '
;

COMMENT ON COLUMN pais.n_nombre_pais
	IS 'nombre del pais de donde puede provenir un fabricante o un cliente '
;

COMMENT ON COLUMN persona.k_identificador
	IS 'ID que se le otorga a la persona de manera interna dentro de la empresa '
;

COMMENT ON COLUMN persona.k_cedula
	IS 'Cedula del supervisor del cliente '
;

COMMENT ON TABLE reporte_servicio
	IS 'Esta tabla se encarga de almacenar los reportes de servicio realizados a cada equipo durante la orden de trabajo.'
;

COMMENT ON COLUMN reporte_servicio.k_id_reporte_servicio
	IS 'Es la llave primaria que actúa como identificador único de los reportes de servicio.'
;

COMMENT ON COLUMN reporte_servicio.k_id_orden_trabajo
	IS 'Es la llave foránea que referencia a la tabla orden_de_trabajo.'
;

COMMENT ON COLUMN reporte_servicio.k_id_equipo_cliente
	IS 'Es la llave foránea que referencia a la tabla equipo_cliente.'
;

COMMENT ON COLUMN reporte_servicio.k_id_cliente
	IS 'Es la llave foránea que referencia a la tabla cliente.'
;

COMMENT ON COLUMN sede.k_id_sede
	IS 'ID con el que se identifica la sede dentro de la empresa'
;

COMMENT ON COLUMN sede.n_nombre_sede
	IS 'nombre de la sede'
;

COMMENT ON COLUMN sede.k_id_cliente
	IS 'Numero de identificacion de las personas que se encuentran en la sede '
;

COMMENT ON COLUMN sede.k_id_ciudad
	IS 'ID de la ciudad en donde se encuentra la sede '
;

COMMENT ON COLUMN telefono_cliente.n_telefono_cliente
	IS 'Número telefonico del cliente '
;

COMMENT ON COLUMN telefono_cliente.k_id_cliente
	IS 'ID del cliente del cual esta relacionado el numero telefonico '
;

COMMENT ON TABLE telefono_persona
	IS 'Esta tabla se encarga de almacenar los números de teléfono asociados a las personas.'
;

COMMENT ON COLUMN telefono_persona.n_telefono_persona
	IS 'Este es el número de teléfono de la persona.'
;

COMMENT ON COLUMN telefono_persona.k_identificador
	IS 'Es la llave foránea que referencia a la tabla persona.'
;

COMMENT ON COLUMN tipo_equipo.k_id_tipo_equipo
	IS 'ID del tipo de equipo'
;

COMMENT ON COLUMN tipo_equipo.n_nombre_tipo_equipo
	IS 'Nombre del tipo de equipo '
;

COMMENT ON COLUMN tipo_equipo.t_definicion_tecnica
	IS 'Definicion tecnica del tipo de equipo, en donde se especifica las caracteristicas que tiene este '
;

COMMENT ON COLUMN tipo_equipo.i_voltage
	IS 'Voltage que tiene cada uno de los diferentes equipos'
;

COMMENT ON COLUMN tipo_equipo.d_amperaje
	IS 'Voltage que tiene cada uno de los diferentes equipos'
;

COMMENT ON COLUMN tipo_equipo.t_tecnologia_predominante
	IS 'Tecnologia predominante que actua en el tipo de equipo '
;

COMMENT ON TABLE verificacion_metrologica
	IS 'Esta tabla se encarga de almacenar las verificaciones metrológicas realizadas a cada equipo durante el mantenimiento.'
;

COMMENT ON COLUMN verificacion_metrologica.d_valor_equipo
	IS 'Este corresponde al valor registrado en la verificación realizada al equipo.'
;

COMMENT ON COLUMN verificacion_metrologica.d_valor_patron
	IS 'Este corresponde al valor registrado del equipo patrón durante la verificación realizada al equipo.'
;

COMMENT ON COLUMN verificacion_metrologica.k_id_reporte_servicio
	IS 'Es la llave foránea que referencia a la tabla reporte_servicio.'
;
